name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  handy_window: ^0.4.0
  flutter_colorpicker: ^1.1.0
  file_picker: ^10.3.3
  flutter_svg: ^2.2.4
  linux_csd_buttons:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/example.json
