name: build example
on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version'
        required: true
        default: '3.35.7'
      flutter_channel:
        description: 'Flutter channel'
        required: true
        default: 'stable'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: ${{ inputs.flutter_channel }}

      - uses: bluefireteam/melos-action@v3

      - name: Build
        working-directory: ./example
        run: flutter build web --base-href "/audioplayers/" --wasm

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./example/build/web

  deploy:
    needs: web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4